import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/main/Header";
import Footer from "@/components/main/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`mx-auto max-w-7xl ${inter.className}`}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
